{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.0.aar",
          "url": "autoussd-sdk-no-sms-3.1.0.aar",
          "size": 228439,
          "sha512": "69b7b17a0a8346041ebfa16bbcf9c0fc39eccb44d85cfbfbcec44c4ff733185c0910bc6903194c3ffd9f49ce40a11fc5d86cbd46a1e54c18c79ea38922ca860c",
          "sha256": "bad223c49671ec2d93ad5c5e06e5e6b65939f4cdf0ab1e7728917fbeab949ab7",
          "sha1": "3152de6c9bd1d4803ff887d2509732ca685fb79a",
          "md5": "bca6698ca2ac3fbeddc72ab6a468d61c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.0.aar",
          "url": "autoussd-sdk-no-sms-3.1.0.aar",
          "size": 228439,
          "sha512": "69b7b17a0a8346041ebfa16bbcf9c0fc39eccb44d85cfbfbcec44c4ff733185c0910bc6903194c3ffd9f49ce40a11fc5d86cbd46a1e54c18c79ea38922ca860c",
          "sha256": "bad223c49671ec2d93ad5c5e06e5e6b65939f4cdf0ab1e7728917fbeab949ab7",
          "sha1": "3152de6c9bd1d4803ff887d2509732ca685fb79a",
          "md5": "bca6698ca2ac3fbeddc72ab6a468d61c"
        }
      ]
    }
  ]
}
