{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.2.aar",
          "url": "autoussd-sdk-no-sms-3.0.2.aar",
          "size": 218222,
          "sha512": "c837042eae0b6c9d26aa7f513d87bcd6fbcf2df7485818525b95a88f57752126c80a5bd9d1f6ae761de90d776490cc328a8ada4725920f3400686e933be5d56a",
          "sha256": "90cd53f92fc243a393f7b595001fd82b9c27fa2f575f1eb9a5e481205013d8ab",
          "sha1": "54aa4be8dda6c58d1de7fb9d373277ad0c8b9f6a",
          "md5": "f82e4ba431de673e21684cb5c51fcae8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.2.aar",
          "url": "autoussd-sdk-no-sms-3.0.2.aar",
          "size": 218222,
          "sha512": "c837042eae0b6c9d26aa7f513d87bcd6fbcf2df7485818525b95a88f57752126c80a5bd9d1f6ae761de90d776490cc328a8ada4725920f3400686e933be5d56a",
          "sha256": "90cd53f92fc243a393f7b595001fd82b9c27fa2f575f1eb9a5e481205013d8ab",
          "sha1": "54aa4be8dda6c58d1de7fb9d373277ad0c8b9f6a",
          "md5": "f82e4ba431de673e21684cb5c51fcae8"
        }
      ]
    }
  ]
}
