{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "4.0.0-alpha-02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0-alpha-02.aar",
          "url": "autoussd-sdk-no-sms-4.0.0-alpha-02.aar",
          "size": 168630,
          "sha512": "ec24ff15e7867c8060977fad05afb63b8662ec3eb206d1f40ffba60e22352323ba3ad5dc13062f29f3c7e606fff82ab469065c703d82c3bda76645f3a50a3327",
          "sha256": "484788d7979fa5663c567f3b663ee2ba154a7cd5f325c761a323487dfe6f4d6c",
          "sha1": "4b05a1d7fd7d4f1b1fc772263bb3aec5ddb91ee5",
          "md5": "a928bb9148ae182851068f6fdfa0c120"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0-alpha-02.aar",
          "url": "autoussd-sdk-no-sms-4.0.0-alpha-02.aar",
          "size": 168630,
          "sha512": "ec24ff15e7867c8060977fad05afb63b8662ec3eb206d1f40ffba60e22352323ba3ad5dc13062f29f3c7e606fff82ab469065c703d82c3bda76645f3a50a3327",
          "sha256": "484788d7979fa5663c567f3b663ee2ba154a7cd5f325c761a323487dfe6f4d6c",
          "sha1": "4b05a1d7fd7d4f1b1fc772263bb3aec5ddb91ee5",
          "md5": "a928bb9148ae182851068f6fdfa0c120"
        }
      ]
    }
  ]
}
