{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.1.aar",
          "url": "autoussd-sdk-no-sms-3.0.1.aar",
          "size": 217383,
          "sha512": "de2a5834fdbde8883fffcebb427a218b35b1273b64550bb8f63c5fbf43b6f0224bb5fb51bac849cf5657ad839a759ce61d309d4fbbfb1503372a32993b73cfcf",
          "sha256": "a8be775d88c319ee623ffc0847c2d9f0b897baf881adb592b22e5a1858aa0604",
          "sha1": "557c912b15c2ceac7947e3cb5be0790bef0b89fa",
          "md5": "ce2d21d1c674e36917dcd3bb652fb758"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.1.aar",
          "url": "autoussd-sdk-no-sms-3.0.1.aar",
          "size": 217383,
          "sha512": "de2a5834fdbde8883fffcebb427a218b35b1273b64550bb8f63c5fbf43b6f0224bb5fb51bac849cf5657ad839a759ce61d309d4fbbfb1503372a32993b73cfcf",
          "sha256": "a8be775d88c319ee623ffc0847c2d9f0b897baf881adb592b22e5a1858aa0604",
          "sha1": "557c912b15c2ceac7947e3cb5be0790bef0b89fa",
          "md5": "ce2d21d1c674e36917dcd3bb652fb758"
        }
      ]
    }
  ]
}
