{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.1.aar",
          "url": "autoussd-sdk-no-sms-3.0.1.aar",
          "size": 217341,
          "sha512": "b8d4727f37dd1342fdd665cd9d52f3fb8babba4a04c4fde124ae5367f136cf6a1fdacf98bf19a437f28dfab7e6aaf1ade5ccfeb05114d54b6abbb51252f4c4f3",
          "sha256": "0919ddfc6c08c6818d23072fc68755d90b9b553e12e23f847e52451884002d45",
          "sha1": "246faad5cd6130437291257e3edcfd8965ae34b2",
          "md5": "9508ea2a99987e079de005ae8282e29f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.0.1.aar",
          "url": "autoussd-sdk-no-sms-3.0.1.aar",
          "size": 217341,
          "sha512": "b8d4727f37dd1342fdd665cd9d52f3fb8babba4a04c4fde124ae5367f136cf6a1fdacf98bf19a437f28dfab7e6aaf1ade5ccfeb05114d54b6abbb51252f4c4f3",
          "sha256": "0919ddfc6c08c6818d23072fc68755d90b9b553e12e23f847e52451884002d45",
          "sha1": "246faad5cd6130437291257e3edcfd8965ae34b2",
          "md5": "9508ea2a99987e079de005ae8282e29f"
        }
      ]
    }
  ]
}
