{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.1.0.aar",
          "url": "autoussd-sdk-no-sms-4.1.0.aar",
          "size": 936672,
          "sha512": "cc6c089a350c199060873b5614ab8236125875b6ad706b91ef3ee5c74ff099c3b8802c4968be9f4dd3744db1edf1736daaf72ea8c5c6aae3882519c0e6af9cb1",
          "sha256": "8113e656d522e76540db9b48345a380a09a4f6ef3fce7de4721dc1b5a432ce41",
          "sha1": "da218d9875ac76a158fb36a692d27ce409d4b2bd",
          "md5": "1c570e3fb992fd9b7ae23cafd2d3d846"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.1.0.aar",
          "url": "autoussd-sdk-no-sms-4.1.0.aar",
          "size": 936672,
          "sha512": "cc6c089a350c199060873b5614ab8236125875b6ad706b91ef3ee5c74ff099c3b8802c4968be9f4dd3744db1edf1736daaf72ea8c5c6aae3882519c0e6af9cb1",
          "sha256": "8113e656d522e76540db9b48345a380a09a4f6ef3fce7de4721dc1b5a432ce41",
          "sha1": "da218d9875ac76a158fb36a692d27ce409d4b2bd",
          "md5": "1c570e3fb992fd9b7ae23cafd2d3d846"
        }
      ]
    }
  ]
}
