{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-0.1.0.aar",
          "url": "autoussd-sdk-no-sms-0.1.0.aar",
          "size": 214306,
          "sha512": "380368432b9d637af6e1bc08cf9e99e4d4ccf3dcccfc49f335fd329c8ae3e1d96009b9e4c3e20c73bb078cadf60e140279baa3bbfabbac32e8df2234670d7307",
          "sha256": "8b4859d9112b7c882d2e5f2416fb9b6bd7b7ce6d38b5a3dd58e8bd286ba5b446",
          "sha1": "b0bdf975a297ed44d1554eca33a0e3a5180ffe8c",
          "md5": "be8d980e6b0cd1a45d451e2798c6b0f5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-0.1.0.aar",
          "url": "autoussd-sdk-no-sms-0.1.0.aar",
          "size": 214306,
          "sha512": "380368432b9d637af6e1bc08cf9e99e4d4ccf3dcccfc49f335fd329c8ae3e1d96009b9e4c3e20c73bb078cadf60e140279baa3bbfabbac32e8df2234670d7307",
          "sha256": "8b4859d9112b7c882d2e5f2416fb9b6bd7b7ce6d38b5a3dd58e8bd286ba5b446",
          "sha1": "b0bdf975a297ed44d1554eca33a0e3a5180ffe8c",
          "md5": "be8d980e6b0cd1a45d451e2798c6b0f5"
        }
      ]
    }
  ]
}
