{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "4.0.0-alpha-01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0-alpha-01.aar",
          "url": "autoussd-sdk-no-sms-4.0.0-alpha-01.aar",
          "size": 168658,
          "sha512": "a000a18cb7583aecbe3157a91d4fb290bc544d6e56d9417a8f862e06c6ebc817fab17684aa9f7963a9ab7710b20b5d5ac98b1f53b130d4077c681a8cab457bf5",
          "sha256": "a107baffbf511c3070774afdf1a0942a2081d0f3a69da4b865babeb7772ef856",
          "sha1": "821f9dd5919be75977a6cf5c6499c39bb57bc920",
          "md5": "8b723aa56a3a27c23d4fa4cd2b626386"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0-alpha-01.aar",
          "url": "autoussd-sdk-no-sms-4.0.0-alpha-01.aar",
          "size": 168658,
          "sha512": "a000a18cb7583aecbe3157a91d4fb290bc544d6e56d9417a8f862e06c6ebc817fab17684aa9f7963a9ab7710b20b5d5ac98b1f53b130d4077c681a8cab457bf5",
          "sha256": "a107baffbf511c3070774afdf1a0942a2081d0f3a69da4b865babeb7772ef856",
          "sha1": "821f9dd5919be75977a6cf5c6499c39bb57bc920",
          "md5": "8b723aa56a3a27c23d4fa4cd2b626386"
        }
      ]
    }
  ]
}
