{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.2.0.aar",
          "url": "autoussd-sdk-no-sms-3.2.0.aar",
          "size": 229406,
          "sha512": "9da44143aa6e8f9b1b4b5c954f5e5763f36e4c4d1bb8ad55733e258cbf4c9ca06cba2f638104a25a87be72c0e8dbd3bdd487262ece6cf5b9af6b2ff0e034e9cb",
          "sha256": "210547848e484fa277933d75b79a508e58efca9c681cf16d69a07aa7dcbd09b0",
          "sha1": "d0f43eaa2d15d1e9b47a61aeda8a3bc786814deb",
          "md5": "b5bcccc48a227ab135b45b06fb925fd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.2.0.aar",
          "url": "autoussd-sdk-no-sms-3.2.0.aar",
          "size": 229406,
          "sha512": "9da44143aa6e8f9b1b4b5c954f5e5763f36e4c4d1bb8ad55733e258cbf4c9ca06cba2f638104a25a87be72c0e8dbd3bdd487262ece6cf5b9af6b2ff0e034e9cb",
          "sha256": "210547848e484fa277933d75b79a508e58efca9c681cf16d69a07aa7dcbd09b0",
          "sha1": "d0f43eaa2d15d1e9b47a61aeda8a3bc786814deb",
          "md5": "b5bcccc48a227ab135b45b06fb925fd2"
        }
      ]
    }
  ]
}
