{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.1.aar",
          "url": "autoussd-sdk-no-sms-3.1.1.aar",
          "size": 229268,
          "sha512": "b6366d1b7e3d526c3604db4bfe1ec1483ca3b90acfcd27677b24c62ec7538b8e199e2f288bfdfead247caeb8cf5fc3c6d9b848e86e5e0d2e9fab37f9aa6aa715",
          "sha256": "f14fe936ecc03be9bdc72301b7de0e18d491158fe84d83cf98774eee60fcd559",
          "sha1": "23b88e3ab34e2a70a7640993b4fedf9d031c4943",
          "md5": "eb82a748bbcabbe4a36df66479e8f7b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.1.aar",
          "url": "autoussd-sdk-no-sms-3.1.1.aar",
          "size": 229268,
          "sha512": "b6366d1b7e3d526c3604db4bfe1ec1483ca3b90acfcd27677b24c62ec7538b8e199e2f288bfdfead247caeb8cf5fc3c6d9b848e86e5e0d2e9fab37f9aa6aa715",
          "sha256": "f14fe936ecc03be9bdc72301b7de0e18d491158fe84d83cf98774eee60fcd559",
          "sha1": "23b88e3ab34e2a70a7640993b4fedf9d031c4943",
          "md5": "eb82a748bbcabbe4a36df66479e8f7b6"
        }
      ]
    }
  ]
}
