{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.1.aar",
          "url": "autoussd-sdk-no-sms-3.1.1.aar",
          "size": 229218,
          "sha512": "404506ec2406ffc5c3674b5902bc85ddc90c2ae5d1988d9f6700dc87c5117b94ec43604b024a0c98c304d79927e59cb89bb33df8e13d32abb8abcb452bfe71a7",
          "sha256": "1cc560f8ddca43c94b98562f8155aca4c984f4996c763ea2402af959440e3c50",
          "sha1": "a443a000712d1cbdffb48a5061ea5c1fd7a43504",
          "md5": "f9bfc37b4c9dae182700a0a1454cc111"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-3.1.1.aar",
          "url": "autoussd-sdk-no-sms-3.1.1.aar",
          "size": 229218,
          "sha512": "404506ec2406ffc5c3674b5902bc85ddc90c2ae5d1988d9f6700dc87c5117b94ec43604b024a0c98c304d79927e59cb89bb33df8e13d32abb8abcb452bfe71a7",
          "sha256": "1cc560f8ddca43c94b98562f8155aca4c984f4996c763ea2402af959440e3c50",
          "sha1": "a443a000712d1cbdffb48a5061ea5c1fd7a43504",
          "md5": "f9bfc37b4c9dae182700a0a1454cc111"
        }
      ]
    }
  ]
}
