{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-1.2.1.aar",
          "url": "autoussd-sdk-no-sms-1.2.1.aar",
          "size": 213944,
          "sha512": "46d710b8c4940573f16f3b8d0c43d79203ffa65d24e35a6475881a926ce336ca3b9f329d2127cd277fe6794d4ecb1e88c0f182ba7a45a87ff78c7f959f6cebdc",
          "sha256": "551adeafb0774428e08e183473e5ae0ca4adbad6c39dfc929462cd6bf7d735c3",
          "sha1": "c5f127931601bc370ca3ee02c1b057d5d90d4f1d",
          "md5": "d3387c3a6b5c9c5f408e2acdf90260c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-1.2.1.aar",
          "url": "autoussd-sdk-no-sms-1.2.1.aar",
          "size": 213944,
          "sha512": "46d710b8c4940573f16f3b8d0c43d79203ffa65d24e35a6475881a926ce336ca3b9f329d2127cd277fe6794d4ecb1e88c0f182ba7a45a87ff78c7f959f6cebdc",
          "sha256": "551adeafb0774428e08e183473e5ae0ca4adbad6c39dfc929462cd6bf7d735c3",
          "sha1": "c5f127931601bc370ca3ee02c1b057d5d90d4f1d",
          "md5": "d3387c3a6b5c9c5f408e2acdf90260c0"
        }
      ]
    }
  ]
}
