{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0.aar",
          "url": "autoussd-sdk-no-sms-4.0.0.aar",
          "size": 935753,
          "sha512": "cc6de4d47c588d37dd85bc26c2638c821b161f6083449ae070b8dbbb5e68397a078f2793754e6c19f5bd90f51e19bb7ecdc86d47d3a1e74a57ffe95dd1bc5153",
          "sha256": "baffe03b55e1d15ca9fa115b62ee5c3bd731ad99ed44364efa8dcf3e434732f3",
          "sha1": "7024667562f2782e2aff32b64a8f43f6dace3fc0",
          "md5": "c670c556ffd56454dfe7593dac708e35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-4.0.0.aar",
          "url": "autoussd-sdk-no-sms-4.0.0.aar",
          "size": 935753,
          "sha512": "cc6de4d47c588d37dd85bc26c2638c821b161f6083449ae070b8dbbb5e68397a078f2793754e6c19f5bd90f51e19bb7ecdc86d47d3a1e74a57ffe95dd1bc5153",
          "sha256": "baffe03b55e1d15ca9fa115b62ee5c3bd731ad99ed44364efa8dcf3e434732f3",
          "sha1": "7024667562f2782e2aff32b64a8f43f6dace3fc0",
          "md5": "c670c556ffd56454dfe7593dac708e35"
        }
      ]
    }
  ]
}
