{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk-no-sms",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-0.1.1.aar",
          "url": "autoussd-sdk-no-sms-0.1.1.aar",
          "size": 214267,
          "sha512": "4d5908da856e2772c29839df9601c5766dcc81a164f16334c5f54dce14518a97783df60d70b288c6c9dd3c9838fe41b39b7f2fdfadb4490d5d350e900348ef8f",
          "sha256": "ba181d5fd27217f2c8ce7d3bec672fb696072d7d5ae07abad85420591ea86eaf",
          "sha1": "cec85a15e065cee2886a6c1726d7c11481e86571",
          "md5": "61e4519870f71964b57b7fc8493b1a94"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-no-sms-0.1.1.aar",
          "url": "autoussd-sdk-no-sms-0.1.1.aar",
          "size": 214267,
          "sha512": "4d5908da856e2772c29839df9601c5766dcc81a164f16334c5f54dce14518a97783df60d70b288c6c9dd3c9838fe41b39b7f2fdfadb4490d5d350e900348ef8f",
          "sha256": "ba181d5fd27217f2c8ce7d3bec672fb696072d7d5ae07abad85420591ea86eaf",
          "sha1": "cec85a15e065cee2886a6c1726d7c11481e86571",
          "md5": "61e4519870f71964b57b7fc8493b1a94"
        }
      ]
    }
  ]
}
